#!/usr/bin/env python3
"""Install qaz."""

import os
import subprocess
import sys


def _msg(msg: str) -> None:
    print(f"\033[1m[QAZ]\033[0m {msg}")


def main() -> int:
    if not (sys.version_info.major == 3 and sys.version_info.minor >= 8):
        print(sys.version)
        print("\033[31mPython 3.8 or later required.\033[0m")
        return 1

    qaz_dir = os.path.dirname(os.path.abspath(__name__))
    qaz_python = os.path.join(qaz_dir, ".venv", "bin", "python")
    qaz_entrypoint = os.path.join(qaz_dir, ".venv", "bin", "qaz")

    _msg("Installing dotfiles and management tool...")

    # Install management tool
    _msg("Installing qaz management tool...")
    subprocess.run(
        ("python3", "-m", "venv", os.path.join(qaz_dir, ".venv")),
        check=True,
    )
    subprocess.run(
        (qaz_python, "-m", "pip", "install", "--upgrade", "pip"),
        check=True,
    )
    subprocess.run(
        (qaz_python, "-m", "pip", "install", qaz_dir),
        check=True,
    )
    subprocess.run(
        ("sudo", "ln", "-sf", qaz_entrypoint, "/usr/local/bin"),
        check=True,
    )
    _msg("... management tool installed!")

    # Run qaz to install basics
    subprocess.run(
        ("mkdir", "-p", os.path.expanduser("~/.config")),
        check=True,
    )
    subprocess.run(
        (qaz_entrypoint, "setup", qaz_dir),
        check=True,
    )

    # Install zsh and set as default shell
    subprocess.run(
        (qaz_entrypoint, "install", "zsh"),
        check=True,
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
