#! /bin/sh
#
# This installs asdf, python, poetry, and qaz.

message() {
    echo "\033[1m[QAZ]\033[0m $@"
}

QAZ=$(pwd)/$(dirname "$0")

message 'Installing dotfiles and management tool...'

# Install asdf
message 'Installing asdf...'
## check if asdf is already installed
if [ ! -x "$(command -v asdf)" ]; then
  ## install asdf
  if [ ! -d $HOME/.asdf ]; then
    git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf
    cd $HOME/.asdf
    git checkout "$(git describe --abbrev=0 --tags)"
  fi
  . $HOME/.asdf/asdf.sh
fi
message '... asdf installed!'

# Install Python
message 'Installing Python...'
asdf plugin add python
set -e  # Exit if Python install fails. This is not unlikely.
asdf install python latest
set +e
asdf shell python $(asdf latest python)
message '... Python installed!'

# Install Poetry
message 'Installing Poetry...'
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
message '... Poetry installed!'

# Install management tool
message "Installing qaz management tool..."
cd $QAZ
asdf exec python -m venv .venv
. .venv/bin/activate
$HOME/.poetry/bin/poetry install --no-dev
sudo ln -sf $QAZ/.venv/bin/qaz /usr/local/bin
message "... management tool installed!"

# Run management tool to install basics
mkdir -p $HOME/.config
$QAZ/.venv/bin/qaz setup $QAZ

# Install zsh and set as default shell
$QAZ/.venv/bin/qaz install zsh
