#! /bin/sh
#
# This installs asdf, python, poetry, and qaz.

QAZ=$(pwd)/$(dirname "$0")

echo 'Installing dotfiles and management tool...'

# Install asdf
echo 'Installing asdf...'
## check if asdf is already installed
if [ ! -x "$(command -v asdf)" ]; then
  ## install asdf
  if [ ! -d $HOME/.asdf ]; then
    git clone https://github.com/asdf-vm/asdf.git $HOME/.asdf
    cd $HOME/.asdf
    git checkout "$(git describe --abbrev=0 --tags)"
  fi
  . $HOME/.asdf/asdf.sh
fi
echo '... asdf installed!'

# Install Python
echo 'Installing Python...'
asdf plugin add python
set -e  # Exit if Python install fails. This is not unlikely.
asdf install python latest
set +e
asdf shell python $(asdf latest python)
echo '... Python installed!'

# Install Poetry
echo 'Installing Poetry...'
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
source $HOME/.poetry/env
echo '... Poetry installed!'

# Install management tool
echo "Installing qaz management tool..."
cd $QAZ
asdf exec python -m venv venv
. venv/bin/activate
poetry install --no-dev
ln -sf $QAZ/venv/bin/qaz /usr/local/bin
echo "... management tool installed!"

# Run management tool to install basics
mkdir -p $HOME/.config
$QAZ/venv/bin/qaz setup $QAZ
