#!/usr/bin/env bash

if [[ $1 = "--fix" ]]; then
    echo ">>> sorting imports..."
    isort .
    echo ">>> auto-formatting..."
    black .
else
    set -e
    echo ">>> checking imports..."
    isort  --check-only .
    echo ">>> checking formatting..."
    black --check .
fi

echo ">>> linting..."
flake8 .
echo ">>> type-checking..."
mypy .
