[tool.poetry]
name = "qaz"
version = "0.1.0"
description = "Manage your system configuration and install/update tools."
authors = ["Samuel Searles-Bryant <devel@samueljsb.co.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
isort = "^4.3.21"
flake8 = "^3.8.3"
flake8-docstrings = "^1.5.0"
mypy = "^0.782"

[tool.poetry.scripts]
qaz = 'qaz.cli:cli'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
