[tool.poetry]
name = "qaz"
version = "0.1.0"
description = "Manage your system configuration and install/update tools."
authors = ["Samuel Searles-Bryant <devel@samueljsb.co.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.6.4"
flake8 = "^3.8.4"
mypy = "^0.790"

[tool.poetry.scripts]
qaz = 'qaz.cli:cli'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
