[tool.poetry]
name = "qaz"
version = "0.1.0"
description = "Manage your system configuration and install/update tools."
authors = ["Samuel Searles-Bryant <devel@samueljsb.co.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
black = "^21.4b0"
isort = "^5.8.0"
flake8 = "^3.9.1"
mypy = "^0.812"

[tool.poetry.scripts]
qaz = 'qaz.cli:cli'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
