from . import brew  # noqa: F401
from . import docker  # noqa: F401
from . import fonts  # noqa: F401
from . import git  # noqa: F401
from . import iterm2  # noqa: F401
from . import latex  # noqa: F401
from . import macos  # noqa: F401
from . import python  # noqa: F401
from . import starship  # noqa: F401
from . import tools  # noqa: F401
from . import vim  # noqa: F401
from . import vscode  # noqa: F401
from . import zsh  # noqa: F401
